name: generate_pdf

# Only run this when the master branch changes
on:
  push:
    branches:
    - test_actions
      #paths:
      #- book/**
# Install the latex things to create the pdf

jobs:
  generate-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install latex dependencies
      run: |
        sudo apt-get install texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Create the pdf version of the book
    - name: Build the pdf book
      run: |
        jupyter-book build . --builder pdflatex
    
    # This next step moves, renames and commits the created pdf
    - name: Commit and rename pdf
      run: |
        mv ./_build/latex/python.pdf codingingis.pdf
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add codingingis.pdf
        git commit -m "update PDF version of the book"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
